language: go

go:
  - 1.8.x
  - tip

before_install:
  - export PATH=$PATH:$HOME/gopath/bin

install:
  - go get github.com/Masterminds/glide
  - glide install

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)