language: go

go:
  - 1.8.x
  - tip
  - stable

before_install:
  - export PATH=$PATH:$HOME/gopath/bin

install:
  - go get github.com/Masterminds/glide
  - glide install
  - go get -v github.com/onsi/ginkgo/ginkgo
  - go get -v github.com/onsi/gomega

script:
  - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress --coverprofile=coverage.txt --covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)